
package andy.happywork.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloServer", targetNamespace = "http://ws.happywork.andy", wsdlLocation = "http://localhost:20213/ws/HelloServer.asmx?WSDL")
public class HelloServer
    extends Service
{

    private final static URL HELLOSERVER_WSDL_LOCATION;
    private final static WebServiceException HELLOSERVER_EXCEPTION;
    private final static QName HELLOSERVER_QNAME = new QName("http://ws.happywork.andy", "HelloServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20213/ws/HelloServer.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSERVER_WSDL_LOCATION = url;
        HELLOSERVER_EXCEPTION = e;
    }

    public HelloServer() {
        super(__getWsdlLocation(), HELLOSERVER_QNAME);
    }

    public HelloServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERVER_QNAME, features);
    }

    public HelloServer(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERVER_QNAME);
    }

    public HelloServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERVER_QNAME, features);
    }

    public HelloServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloServerSoap
     */
    @WebEndpoint(name = "HelloServerSoap")
    public HelloServerSoap getHelloServerSoap() {
        return super.getPort(new QName("http://ws.happywork.andy", "HelloServerSoap"), HelloServerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloServerSoap
     */
    @WebEndpoint(name = "HelloServerSoap")
    public HelloServerSoap getHelloServerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.happywork.andy", "HelloServerSoap"), HelloServerSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERVER_EXCEPTION!= null) {
            throw HELLOSERVER_EXCEPTION;
        }
        return HELLOSERVER_WSDL_LOCATION;
    }

}
